INFO:__main__:PEX 03 start.
INFO:__main__:Connecting to device...
INFO:autopilot:ArduCopter V4.1.0-dev (428c9ef0)
INFO:autopilot:a3d9197b765643568af09eb2bd3e5ce7
INFO:autopilot:Frame: QUAD
INFO:__main__:Device connected.
INFO:root:Device version: APM:Copter-None.None.NoneUnknownReleaseType, log=
INFO:__main__:Looking for mission to execute...
INFO:__main__:Arming device...
INFO:__main__:Device armed: True.
INFO:__main__:Device takeoff...
INFO:__main__:Current altitude: 20.001
INFO:__main__:Changing device mode from VehicleMode:GUIDED to AUTO...
INFO:autopilot:Mission: 3 WP
INFO:__main__:Device mode = VehicleMode:AUTO.
INFO:__main__:backing up old images...
INFO:root:Searching for target...
INFO:root:Changing device mode from VehicleMode:AUTO to GUIDED...
INFO:root:Device mode = VehicleMode:GUIDED.
INFO:__main__:Goto point: 21.3212522, -157.9240414, 1, 20.0...
INFO:__main__:Current altitude: 20.002
INFO:__main__:Current lat: 21.3212545
INFO:root:Current lon: (-157.9240509, <Logger __main__ (DEBUG)>)
INFO:__main__:Relative position to destination: 1.0001,1.0000001078735892, 1.0000000601555021
INFO:__main__:Program exception: ['Traceback (most recent call last):\n', '  File "/home/usafa/PycharmProjects/USAFA/PEX3-COMP495/mission.py", line 658, in <module>\n    conduct_mission()\n', '  File "/home/usafa/PycharmProjects/USAFA/PEX3-COMP495/mission.py", line 550, in conduct_mission\n    determine_drone_actions((last_lat, last_lon), frm_display, target_sightings, ogbbox)\n', '  File "/home/usafa/PycharmProjects/USAFA/PEX3-COMP495/mission.py", line 593, in determine_drone_actions\n    distance = get_ground_distance(drone.location.global_relative_frame.alt, hypo)\n', '  File "/home/usafa/PycharmProjects/USAFA/PEX3-COMP495/mission.py", line 584, in get_ground_distance\n    return math.sqrt(hypotenuse ** 2 - height ** 2)\n', 'ValueError: math domain error\n']
